image_parameters:
  height_og: 800
  img_path: ../img/static_frame_from_video.jpg
  p1:
  - 47
  - 273
  p2:
  - 329
  - 145
  p3:
  - 508
  - 519
  p4:
  - 794
  - 236
  size_frame: '800'
  width_og: 600
