image_parameters:
  height_og: 800
  img_path: ../img/static_frame_from_video.jpg
  p1:
  - 546
  - 503
  p2:
  - 799
  - 248
  p3:
  - 68
  - 298
  p4:
  - 343
  - 143
  size_frame: '800'
  width_og: 600
