image_parameters:
  height_og: 1280
  img_path: ../img/static_frame_from_video.jpg
  p1:
  - 73
  - 398
  p2:
  - 640
  - 67
  p3:
  - 1110
  - 615
  p4:
  - 1222
  - 102
  size_frame: '1280'
  width_og: 720
